spring:
  application:
    name: consumer-server
  cloud:
    bus:
      enabled: true
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: refresh
feign:
  hystrix:
    enabled: true
